version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .env
    ports:
      - "9653:5000"
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_DB: $POSTGRES_DB
    # ADD THESE LINES
    logging:
        driver: "json-file"
        options:
            max-size: "10m"
            max-file: "3"
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_directory=pg_log", "-c", "log_destination=stderr", "-c", "log_line_prefix=%t %p %u@%d %a"]

volumes:
  postgres-data: